version: '3'

services:
  mongodb:
    image: mongo:4.1.11
    container_name: group-communication-survey-mongodb
    restart: always
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/exports:/var/mongodb/exports
      - ./mongodb/meta:/var/mongodb/meta
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
  api:
    container_name: group-communication-survey-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    restart: always
    ports:
      - '4000:4000'
