version: '3'

services:
  mongodb:
    image: mongo:4.1.11
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
